"use client";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import StudentShell from "@/components/StudentShell";
const money = (v) => new Intl.NumberFormat("en-GH", { style: "currency", currency: "GHS" }).format(Number(v || 0));
const date = (v) => v ? new Intl.DateTimeFormat("en-GB").format(new Date(v)) : "—";

function Table({ headings, children, empty }) { return <div className="table-wrap"><table><thead><tr>{headings.map((h) => <th key={h}>{h}</th>)}</tr></thead><tbody>{children || <tr><td colSpan={headings.length} className="empty">{empty}</td></tr>}</tbody></table></div>; }

export default function StudentModule({ type }) {
  const config = { profile: ["Personal Information", "/api/me"], courses: ["My Courses", "/api/my-courses"], enrollments: ["My Enrollments", "/api/my-courses"], fees: ["My Fees", "/api/my-fees"], payments: ["My Payments", "/api/my-payments"], outstanding: ["Outstanding Fees", "/api/my-outstanding-fees"] }[type];
  const [data, setData] = useState(null); const [error, setError] = useState("");
  const router = useRouter();
  useEffect(() => { fetch(config[1]).then(async (r) => { const body = await r.json(); if (r.status === 401) { router.replace("/login"); return null; } if (!r.ok) throw new Error(body.error || "Unable to load this page."); return body.data; }).then((body) => { if (body) setData(body); }).catch((e) => setError(e.message === "Failed to fetch" ? "Unable to reach the server. Please refresh and try again." : e.message)); }, [type, router]);
  let content = <p>Loading {config[0].toLowerCase()}…</p>;
  if (error) content = <p className="form-message">{error}</p>;
  if (data && type === "profile") content = <section className="panel details"><p><span>Student ID</span>{data.student_id}</p><p><span>Full name</span>{data.name}</p><p><span>Programme</span>{data.programme || "—"}</p><p><span>Email</span>{data.email || "—"}</p><p><span>Phone</span>{data.phone || "—"}</p></section>;
  if (data && (type === "courses" || type === "enrollments")) content = <section className="panel"><Table headings={type === "courses" ? ["Course ID", "Course name", "Credit hours", "Lecturer"] : ["Course ID", "Course name", "Enrollment", "Credit hours", "Lecturer"]} empty="No enrolled courses found.">{data.length && data.map((c) => <tr key={c.course_id}><td>{c.course_id}</td><td>{c.course_name}</td>{type === "enrollments" && <td>{date(c.enrollment_date)}</td>}<td>{c.credit_hours || "—"}</td><td>{c.lecturer}</td></tr>)}</Table></section>;
  if (data && type === "fees") { const due=data.reduce((s,x)=>s+Number(x.amount_due),0), paid=data.reduce((s,x)=>s+Number(x.amount_paid),0); content=<><section className="stat-grid"><article className="summary-card"><span>Total fees</span><strong>{money(due)}</strong></article><article className="summary-card"><span>Amount paid</span><strong>{money(paid)}</strong></article><article className="summary-card"><span>Outstanding</span><strong>{money(due-paid)}</strong></article></section><section className="panel"><Table headings={["Academic year","Fee type","Due","Paid","Outstanding"]} empty="No fee records found.">{data.length && data.map((f)=><tr key={f.fee_id}><td>{f.academic_year}</td><td>{f.fee_type}</td><td>{money(f.amount_due)}</td><td>{money(f.amount_paid)}</td><td>{money(f.outstanding_balance)}</td></tr>)}</Table></section></>; }
  if (data && type === "payments") content=<section className="panel"><Table headings={["Payment ID","Reference","Amount paid","Payment date","Related fee"]} empty="No payment records found.">{data.length && data.map((p)=><tr key={p.payment_id}><td>{p.payment_id || "—"}</td><td>{p.payment_reference || "—"}</td><td>{money(p.amount_paid)}</td><td>{date(p.payment_date)}</td><td>{p.fee_id || "—"}</td></tr>)}</Table></section>;
  if (data && type === "outstanding") { const fees=data.fees || []; const due=fees.reduce((s,x)=>s+Number(x.total_fee),0), paid=fees.reduce((s,x)=>s+Number(x.total_paid),0); content=<><section className="stat-grid"><article className="summary-card"><span>Total amount due</span><strong>{money(due)}</strong></article><article className="summary-card"><span>Total amount paid</span><strong>{money(paid)}</strong></article><article className="summary-card"><span>Outstanding balance</span><strong>{money(data.totalOutstanding)}</strong></article></section><section className="panel"><Table headings={["Academic year","Fee type","Outstanding"]} empty="No outstanding fee records found.">{fees.length && fees.map((f)=><tr key={f.fee_id}><td>{f.academic_year || "—"}</td><td>{f.fee_type || "—"}</td><td>{money(f.outstanding_balance)}</td></tr>)}</Table></section></>; }
  return <StudentShell><header className="page-title"><p className="eyebrow">Student portal</p><h1>{config[0]}</h1></header>{content}</StudentShell>;
}
