import pool from "@/lib/db";
import { databaseError, failure, success } from "@/lib/api";
import { requireAdmin } from "@/lib/admin";

const queries = {
  courses: `SELECT c.course_id, c.course_name, c.credit_hours, COALESCE(string_agg(DISTINCT l.name, ', '),'Unassigned') AS lecturer, COUNT(DISTINCT e.enrollment_id)::int AS enrolled_students FROM courses c LEFT JOIN course_lecturers cl ON cl.course_id=c.course_id LEFT JOIN lecturers l ON l.lecturer_id=cl.lecturer_id LEFT JOIN enrollments e ON e.course_id=c.course_id GROUP BY c.course_id ORDER BY c.course_id`,
  enrollments: `SELECT e.enrollment_id, s.student_id, s.name AS student_name, c.course_id, c.course_name, e.enrollment_date FROM enrollments e JOIN students s ON s.student_id=e.student_id JOIN courses c ON c.course_id=e.course_id ORDER BY e.enrollment_date DESC`,
  lecturers: `SELECT l.lecturer_id, l.name, l.email, COALESCE(string_agg(DISTINCT c.course_name, ', '),'None') AS assigned_courses, COALESCE(string_agg(DISTINCT ta.name, ', '),'None') AS assigned_tas FROM lecturers l LEFT JOIN course_lecturers cl ON cl.lecturer_id=l.lecturer_id LEFT JOIN courses c ON c.course_id=cl.course_id LEFT JOIN lecturer_tas lt ON lt.lecturer_id=l.lecturer_id LEFT JOIN teaching_assistants ta ON ta.ta_id=lt.ta_id GROUP BY l.lecturer_id ORDER BY l.lecturer_id`,
  "teaching-assistants": `SELECT ta.ta_id, ta.name, ta.email, COALESCE(string_agg(DISTINCT l.name, ', '),'Unassigned') AS lecturer FROM teaching_assistants ta LEFT JOIN lecturer_tas lt ON lt.ta_id=ta.ta_id LEFT JOIN lecturers l ON l.lecturer_id=lt.lecturer_id GROUP BY ta.ta_id ORDER BY ta.ta_id`,
  "lecturer-courses": `SELECT c.course_id, c.course_name, l.lecturer_id, l.name AS lecturer_name FROM course_lecturers cl JOIN courses c ON c.course_id=cl.course_id JOIN lecturers l ON l.lecturer_id=cl.lecturer_id ORDER BY c.course_id`,
  "lecturer-tas": `SELECT l.lecturer_id, l.name AS lecturer_name, ta.ta_id, ta.name AS ta_name FROM lecturer_tas lt JOIN lecturers l ON l.lecturer_id=lt.lecturer_id JOIN teaching_assistants ta ON ta.ta_id=lt.ta_id ORDER BY l.lecturer_id`,
  fees: `SELECT s.student_id, s.name AS student_name, f.academic_year, f.fee_type, f.amount_due, COALESCE(SUM(p.amount_paid),0) AS amount_paid, f.amount_due-COALESCE(SUM(p.amount_paid),0) AS outstanding FROM fees f JOIN students s ON s.student_id=f.student_id LEFT JOIN payments p ON p.fee_id=f.fee_id GROUP BY f.fee_id,s.student_id,s.name ORDER BY s.student_id`,
  payments: `SELECT p.payment_id, s.student_id, s.name AS student_name, p.amount_paid, p.payment_date, p.payment_reference FROM payments p JOIN students s ON s.student_id=p.student_id ORDER BY p.payment_date DESC`,
  "outstanding-balances": `SELECT s.student_id, s.name, COALESCE(SUM(f.amount_due),0) AS total_due, COALESCE(SUM(p.paid),0) AS total_paid, COALESCE(SUM(f.amount_due),0)-COALESCE(SUM(p.paid),0) AS outstanding_balance FROM students s LEFT JOIN fees f ON f.student_id=s.student_id LEFT JOIN (SELECT fee_id,SUM(amount_paid) AS paid FROM payments GROUP BY fee_id) p ON p.fee_id=f.fee_id GROUP BY s.student_id,s.name HAVING COALESCE(SUM(f.amount_due),0)>COALESCE(SUM(p.paid),0) ORDER BY outstanding_balance DESC`,
  users: `SELECT u.user_id,u.email,u.student_id,u.role,CASE WHEN u.role='admin' THEN 'Administrator account' ELSE 'Student account' END AS account_status FROM users u ORDER BY u.user_id`
};
export async function GET(request,{params}){const denied=requireAdmin();if(denied)return denied;const query=queries[params.resource];if(!query)return failure("Unknown admin resource.",404);try{return success((await pool.query(query)).rows)}catch(error){return databaseError(error)}}
